tittle: Ekele Enenche James
logo:
description:A science student turned DevOps engineer, I embarked on my tech journey through a government scholarship. With a passion for creating efficient CI/CD pipelines and robust cloud infrastructures, I've thrived in the dynamic world of technology for over four years.
show_downloads: true
theme: 
